name: Build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:

  build-opensuse:
    name: Build openSUSE
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensuse_version: [ 'tumbleweed', 'leap:15.6', 'leap:16.0' ]
    container:
      image: opensuse/${{matrix.opensuse_version}}
    steps:
      - name: Refresh repositories
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages (Tumbleweed)
        if: matrix.opensuse_version == 'tumbleweed'
        run: zypper -n --gpg-auto-import-keys dup
      - name: Upgrade packages (Leap)
        if: matrix.opensuse_version != 'tumbleweed'
        run: zypper -n --gpg-auto-import-keys up
      - name: Install gcc
        if: matrix.opensuse_version != 'leap:15.6'
        run: zypper -n --gpg-auto-import-keys in gcc gcc-c++
      - name: Install gcc (leap:15.6)
        if: matrix.opensuse_version == 'leap:15.6'
        run: zypper -n --gpg-auto-import-keys in gcc14 gcc14-c++
      - name: Install packages
        run: >
            zypper -n --gpg-auto-import-keys in
            lsb-release rpm-build git tar make cmake openssh-clients glibc-devel
            libboost_headers-devel boost-devel glib2-devel glib2-tools alsa-devel
            libnotify-devel sqlite3-devel libpulse-devel gstreamer-devel
            gstreamer-plugins-base-devel taglib-devel libicu-devel libcdio-devel
            libgpod-devel libmtp-devel libchromaprint-devel fftw3-devel
            libebur128-devel desktop-file-utils update-desktop-files appstream-glib
            hicolor-icon-theme qt6-core-devel qt6-gui-devel qt6-gui-private-devel
            qt6-widgets-devel qt6-concurrent-devel qt6-network-devel qt6-sql-devel
            qt6-dbus-devel qt6-test-devel qt6-base-common-devel qt6-sql-sqlite
            qt6-linguist-devel gtest gmock sparsehash-devel
      - name: Install kdsingleapplication-qt6-devel
        if: matrix.opensuse_version != 'leap:15.6'
        run: zypper -n --gpg-auto-import-keys in kdsingleapplication-qt6-devel
      - name: Build and install KDSingleApplication
        if: matrix.opensuse_version == 'leap:15.6'
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          git clone --depth 1 --recurse-submodules https://github.com/KDAB/KDSingleApplication
          cd KDSingleApplication
          cmake -S . -B build -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DKDSingleApplication_STATIC=ON
          cmake --build build --config Release --parallel 4
          cmake --install build
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_WERROR=ON
      - name: Create source tarball
        working-directory: build
        run: ../dist/scripts/maketarball.sh
      - name: Create RPM build sources directories
        run: mkdir -p ~/rpmbuild/SOURCES /usr/src/packages/SOURCES
      - name: Copy source tarball
        working-directory: build
        run: cp strawberry-*.tar.xz /usr/src/packages/SOURCES/
      - name: Build RPM
        if: matrix.opensuse_version != 'leap:15.6'
        env:
          RPM_BUILD_NCPUS: 4
        working-directory: build
        run: rpmbuild -ba strawberry.spec
      - name: Build RPM (leap:15.6)
        if: matrix.opensuse_version == 'leap:15.6'
        env:
          RPM_BUILD_NCPUS: 4
          CC: gcc-14
          CXX: g++-14
        working-directory: build
        run: rpmbuild -ba strawberry.spec
      - name: Set subdir
        id: set-subdir
        run: echo "subdir=$(echo ${{matrix.opensuse_version}} | sed 's/leap:/lp/g' | sed 's/\.//g')" > $GITHUB_OUTPUT
      - name: Upload source
        if: matrix.opensuse_version == 'tumbleweed'
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: /usr/src/packages/SOURCES/*.xz
      - name: Upload rpm
        if: matrix.opensuse_version != 'tumbleweed'
        uses: actions/upload-artifact@v4
        with:
          name: opensuse-${{steps.set-subdir.outputs.subdir}}
          path: |
            /usr/src/packages/SRPMS/*.rpm
            /usr/src/packages/RPMS/x86_64/*.rpm

  build-fedora:
    name: Build Fedora
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_version: [ '42', '43', '44' ]
    container:
      image: fedora:${{matrix.fedora_version}}
    steps:
      - name: Update repositories
        run: dnf -y update
      - name: Upgrade packages
        run: dnf -y upgrade
      - name: Install dependencies
        run: >
            dnf -y install
            @development-tools lsb_release which git glibc gcc-c++ rpmdevtools
            make cmake pkgconfig glib man tar openssh rsync boost-devel
            sqlite-devel alsa-lib-devel pulseaudio-libs-devel libnotify-devel
            libicu-devel qt6-qtbase-devel qt6-qtbase-private-devel qt6-qttools-devel
            gstreamer1-devel gstreamer1-plugins-base-devel taglib-devel libcdio-devel
            libgpod-devel libmtp-devel libchromaprint-devel libebur128-devel
            fftw-devel desktop-file-utils libappstream-glib hicolor-icon-theme
            kdsingleapplication-qt6-devel gtest-devel gmock-devel sparsehash-devel
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_WERROR=ON
      - name: Create source tarball
        working-directory: build
        run: ../dist/scripts/maketarball.sh
      - name: Create RPM build sources directories
        working-directory: build
        run: mkdir -p ~/rpmbuild/SOURCES /usr/src/packages/SOURCES
      - name: Copy source tarball
        working-directory: build
        run: cp strawberry-*.tar.xz ~/rpmbuild/SOURCES/
      - name: Build RPM
        env:
          RPM_BUILD_NCPUS: 4
        working-directory: build
        run: rpmbuild -ba strawberry.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fedora-${{matrix.fedora_version}}
          path: |
            /github/home/rpmbuild/SRPMS/*.rpm
            /github/home/rpmbuild/RPMS/x86_64/*.rpm

  build-mageia:
    name: Build Mageia
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mageia_version: [ '9' ]
    container:
      image: mageia:${{matrix.mageia_version}}
    steps:
      - name: Update repositories
        run: urpmi.update -a
      - name: Upgrade packages
        run: urpmi --auto --auto-update
      - name: Install dependencies
        run: >
          urpmi --auto --force urpmi-debuginfo-install
          git glibc gcc-c++ binutils make cmake man tar rpmdevtools
          lib64boost-devel lib64sqlite3-devel lib64alsa2-devel lib64pulseaudio-devel
          lib64gstreamer1.0-devel lib64gstreamer-plugins-base1.0-devel lib64cdio-devel
          lib64gpod-devel lib64mtp-devel lib64taglib-devel lib64chromaprint-devel
          lib64ebur128-devel lib64icu-devel lib64fftw-devel lib64dbus-devel
          lib64appstream-devel lib64qt6core-devel lib64qt6gui-devel lib64qt6widgets-devel
          lib64qt6network-devel lib64qt6concurrent-devel lib64qt6sql-devel
          lib64qt6dbus-devel lib64qt6help-devel lib64qt6test-devel lib64sparsehash-devel
          lib64kdsingleapplication-devel desktop-file-utils appstream-util
          hicolor-icon-theme gtest
      - name: Build and install KDSingleApplication
        if: matrix.mageia_version == '9'
        run: |
          git clone --depth 1 --recurse-submodules https://github.com/KDAB/KDSingleApplication
          cd KDSingleApplication
          cmake -S . -B build -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DKDSingleApplication_STATIC=ON
          cmake --build build --config Release --parallel 4
          cmake --install build
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_WERROR=ON
      - name: Create source tarball
        working-directory: build
        run: ../dist/scripts/maketarball.sh
      - name: Create RPM build sources directories
        working-directory: build
        run: mkdir -p ~/rpmbuild/SOURCES /usr/src/packages/SOURCES
      - name: Copy source tarball
        working-directory: build
        run: cp strawberry-*.tar.xz ~/rpmbuild/SOURCES/
      - name: Build RPM
        env:
          RPM_BUILD_NCPUS: 4
        working-directory: build
        run: rpmbuild -ba strawberry.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mageia-${{matrix.mageia_version}}
          path: |
            /github/home/rpmbuild/SRPMS/*.rpm
            /github/home/rpmbuild/RPMS/x86_64/*.rpm

  build-debian:
    name: Build Debian
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian_version: [ 'bookworm', 'trixie', 'forky' ]
    container:
      image: debian:${{matrix.debian_version}}
    steps:
      - name: Update packages
        run: apt update -y
      - name: Upgrade packages
        run: apt upgrade -y
      - name: Install packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >
            apt install -y
            build-essential dh-make git make cmake gcc g++ pkg-config fakeroot
            lsb-release dpkg-dev libglib2.0-dev libboost-dev libsqlite3-dev
            libasound2-dev libpulse-dev libtag1-dev libicu-dev libgstreamer1.0-dev
            libgstreamer-plugins-base1.0-dev gstreamer1.0-alsa gstreamer1.0-pulseaudio
            libchromaprint-dev libebur128-dev libfftw3-dev libcdio-dev libmtp-dev
            libgpod-dev libxkbcommon-dev libsparsehash-dev qt6-base-dev
            qt6-base-private-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools
            qt6-l10n-tools
      - name: Install KDSingleApplication
        if: matrix.debian_version != 'bookworm'
        run: apt install -y libkdsingleapplication-qt6-dev
      - name: Build and install KDSingleApplication
        if: matrix.debian_version == 'bookworm'
        run: |
          git clone --depth 1 --recurse-submodules https://github.com/KDAB/KDSingleApplication
          cd KDSingleApplication
          cmake -S . -B build -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DKDSingleApplication_STATIC=ON
          cmake --build build --config Release --parallel 4
          cmake --install build
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_WERROR=ON
      - name: Delete build directory
        run: rm -rf build
      - name: make deb
        run: dpkg-buildpackage -b -d -uc -us -nc -j4
      - name: Copy deb
        run: cp ../*.deb .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-${{matrix.debian_version}}
          path: '*.deb'

  build-ubuntu:
    name: Build Ubuntu
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [ 'noble', 'questing', 'resolute' ]
    container:
      image: ubuntu:${{matrix.ubuntu_version}}
    steps:
      - name: Update packages
        run: apt update -y
      - name: Upgrade packages
        run: apt upgrade -y
      - name: Install packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >
            apt install -y
            build-essential dh-make git make cmake pkg-config gcc g++ fakeroot
            wget curl lsb-release dpkg-dev libglib2.0-dev libboost-dev libsqlite3-dev
            libasound2-dev libpulse-dev libtag1-dev libicu-dev libgstreamer1.0-dev
            libgstreamer-plugins-base1.0-dev gstreamer1.0-alsa gstreamer1.0-pulseaudio
            libchromaprint-dev libebur128-dev libfftw3-dev libcdio-dev libmtp-dev
            libgpod-dev libxkbcommon-dev libsparsehash-dev qt6-base-dev
            qt6-base-private-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools
            qt6-l10n-tools
      - name: Install KDSingleApplication
        if: matrix.ubuntu_version != 'noble'
        run: apt install -y libkdsingleapplication-qt6-dev
      - name: Build and install KDSingleApplication
        if: matrix.ubuntu_version == 'noble'
        run: |
          git clone --depth 1 --recurse-submodules https://github.com/KDAB/KDSingleApplication
          cd KDSingleApplication
          cmake -S . -B build -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DKDSingleApplication_STATIC=ON
          cmake --build build --config Release --parallel 4
          cmake --install build
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_WERROR=ON
      - name: Delete build directory
        run: rm -rf build
      - name: make deb
        run: dpkg-buildpackage -b -d -uc -us -nc -j4
      - name: Copy deb
        run: cp ../*.deb ../*.ddeb .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{matrix.ubuntu_version}}
          path: |
            *.deb
            *.ddeb

  build-macos-public:
    name: Build macOS Public
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    strategy:
      fail-fast: false
      matrix:
        runner: [ 'macos-15-intel', 'macos-15' ]
        buildtype: [ 'release' ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set MACOSX_DEPLOYMENT_TARGET
        run: |
          for i in 12 13 14 15; do
            if [ -d "/Library/Developer/CommandLineTools/SDKs/MacOSX${i}.sdk" ]; then
              echo "Using macOS SDK ${i}"
              echo "MACOSX_DEPLOYMENT_TARGET=${i}.0" >> $GITHUB_ENV
              break
            fi
          done
      - name: Verify MACOSX_DEPLOYMENT_TARGET
        run: |
          test "${MACOSX_DEPLOYMENT_TARGET}" = "" && false || echo "MACOSX_DEPLOYMENT_TARGET: ${MACOSX_DEPLOYMENT_TARGET}"
      - name: Set arch
        shell: bash
        run: echo "arch=$(uname -m)" >> $GITHUB_ENV
      - name: Set buildtype
        run: echo "buildtype=$(echo ${{matrix.buildtype}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Set cmake buildtype
        run: echo "cmake_buildtype=$(echo ${{env.buildtype}} | awk '{print toupper(substr($0,0,1))tolower(substr($0,2))}')" >> $GITHUB_ENV
      - name: Uninstall homebrew
        run: |
          curl -sfLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force
          rm -f uninstall.sh
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Download macOS dependencies
        run: curl -f -O -L https://github.com/strawberrymusicplayer/strawberry-macos-dependencies/releases/latest/download/strawberry-macos-${{env.arch}}-${{env.buildtype}}.tar.xz
      - name: Extract macOS dependencies
        run: sudo tar -C / -xf strawberry-macos-${{env.arch}}-${{env.buildtype}}.tar.xz
      - name: Set prefix path
        run: echo "prefix_path=/opt/strawberry_macos_${{env.arch}}_${{env.buildtype}}" >> $GITHUB_ENV
      - name: Update PATH
        run: echo "${{env.prefix_path}}/bin" >> $GITHUB_PATH
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        env:
          PKG_CONFIG_PATH: ${{env.prefix_path}}/lib/pkgconfig
          LDFLAGS: -L${{env.prefix_path}}/lib -Wl,-rpath,${{env.prefix_path}}/lib
        run: >
          cmake
          --log-level="DEBUG"
          -S .
          -B build
          -DCMAKE_BUILD_TYPE="${{env.cmake_buildtype}}"
          -DCMAKE_PREFIX_PATH="${{env.prefix_path}}/lib/cmake"
          -DBUILD_WERROR=ON
          -DUSE_BUNDLE=ON
          -DICU_ROOT="${{env.prefix_path}}"
          -DARCH="${{env.arch}}"
          -DENABLE_SPOTIFY=$(test -f "${{env.prefix_path}}/lib/gstreamer-1.0/libgstspotify.dylib" && echo "ON" || echo "OFF")
          -DENABLE_SPARKLE=ON
          -DENABLE_QTSPARKLE=OFF
      - name: Build
        run: cmake --build build --config Release --parallel 4
      - name: Install
        working-directory: build
        run: make install
      - name: Deploy
        env:
          GIO_EXTRA_MODULES: ${{env.prefix_path}}/lib/gio/modules
          GST_PLUGIN_SCANNER: ${{env.prefix_path}}/libexec/gstreamer-1.0/gst-plugin-scanner
          GST_PLUGIN_PATH: ${{env.prefix_path}}/lib/gstreamer-1.0
          LIBSOUP_LIBRARY_PATH: ${{env.prefix_path}}/lib/libsoup-3.0.0.dylib
        working-directory: build
        run: make deploy
      - name: Create DMG
        working-directory: build
        run: make dmg
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{matrix.runner}}-${{matrix.buildtype}}
          path: build/**/*.dmg

  build-windows-msvc:
    name: Build Windows MSVC
    if: (github.event_name == 'push' && github.ref_name != 'l10n_master') ||
        (github.event_name == 'pull_request' && github.head_ref != 'l10n_master') ||
        (github.event_name == 'release')
    strategy:
      fail-fast: false
      matrix:
       include:
          - name: "x86_64 release"
            runner: windows-2022
            arch: x86_64
            buildtype: release
          - name: "arm64 release"
            runner: windows-11-arm
            arch: arm64
            buildtype: release
    runs-on: ${{matrix.runner}}
    steps:
      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Download Windows MSVC dependencies
        shell: cmd
        run: curl -f -O -L https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/releases/latest/download/strawberry-msvc-${{matrix.arch}}-${{matrix.buildtype}}.tar.xz
      - name: Extract Windows MSVC dependencies
        shell: bash
        run: tar -C /c -xf strawberry-msvc-${{matrix.arch}}-${{matrix.buildtype}}.tar.xz
      - name: Build and Package
        shell: cmd
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel 4
          cd build && makensis strawberry.nsi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-${{matrix.arch}}-${{matrix.buildtype}}
          path: build/**/*.exe

  attach:
    name: Attach to release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-macos-public
      - build-windows-msvc
      - build-ubuntu
      - build-debian
      - build-fedora
      - build-mageia
      - build-opensuse
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Processing artifacts..."
          find artifacts -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.deb" -o -name "*.rpm" \) -exec gh release upload ${{ github.event.release.tag_name }} {} --clobber \;